### ISSUE TITLE
make problem

### ISSUE THREAD

**Issue by SihyeongPark** [emeryberger/CSrankings#243]
Hi, I'm trying to build oneself CS ranking. I cloned this repo and installed some utils like libxm2-utils and so on. Also I finished 'make update-dblp' then when I type make there is some error like below:

**$ make**
Rebuilding the publication database (generated-author-info.csv).
pypy util/regenerate-data.py
Traceback (most recent call last):
  File "util/regenerate-data.py", line 106, in <module>
    (intauthors_gl, authscores_gl, authscoresAdjusted_gl, authlog_gl) = parseDBLP(fdict)
  File "util/regenerate-data.py", line 20, in parseDBLP
    for (event, node) in ElementTree.iterparse(f, events=['start', 'end']):
  File "/usr/lib/pypy/lib-python/2.7/xml/etree/ElementTree.py", line 1281, in next
    self._root = self._parser.close()
  File "/usr/lib/pypy/lib-python/2.7/xml/etree/ElementTree.py", line 1664, in close
    self._raiseerror(v)
  File "/usr/lib/pypy/lib-python/2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: no element found: line 1, column 0
Makefile:44: recipe for target 'generated-author-info.csv' failed
make: *** [generated-author-info.csv] Error 1

How can I fix this?

**Comment by emeryberger** [comment]
I have never seen this kind of error, sorry.

**Comment by emeryberger** [comment]
Ugh, found the problem and fixed it.

**Comment by SihyeongPark** [comment]
Thank you, emeryberger.
